# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PhPfAttO5JjQ4GrOl_A-ElOt00PqcvqF
"""

class Foguete:
    def __init__(self, tamanho, velocidade, material):
        self.tamanho = tamanho
        self.velocidade = velocidade
        self.material = material

    def voar(self):
        print("o foguete esta voando")

    def explodir(self):
        print("o foguete explodiu")


foguete1 = Foguete(tamanho=50, velocidade=20000, material="ferro")

foguete1.voar()
foguete1.explodir()
print(foguete1.tamanho, foguete1.velocidade, foguete1.material)

class ContaBanco:
    def __init__(self, titular, saldo_inicial=0):
        self.titular = titular
        self.__saldo = saldo_inicial

    def get_saldo(self):
        return self.__saldo

    def depositar(self, valor):
        if valor > 0:
            self.__saldo += valor
            print(f"Depósito de R$ {valor} realizado")
        else:
            print("O valor deve ser positivo")

    def sacar(self, valor):
        if valor > self.__saldo:
            print("Saldo insuficiente")
        elif valor <= 0:
            print("O valor do saque deve ser positivo")
        else:
            self.__saldo -= valor
            print(f"Saque de R$ {valor} realizado")

conta = ContaBanco("Leo", 500)
conta.depositar(50)
conta.sacar(50)
print(f"Saldo atual: R$ {conta.get_saldo()}")

class Animal:

  def __init__(self, nome):
    self.nome = nome

  def comer(self):
    print(f"{self.nome} esta comendo")


class Mamifero(Animal):

  def amamentar(self):
    print(f"{self.nome} esta amamentando")


class Cachorro(Mamifero):

  def emitir_som(self):
    print(f"{self.nome} Au Au")

class Gato(Mamifero):

  def emitir_som(self):
    print(f"{self.nome} Miau")
class Passaro(Animal):

  def emitir_som(self):
    print(f"{self.nome} Pit Pit")


Vandog = Cachorro("Vandog")
Miaumiau = Gato("Miaumiau")
Piriquito = Passaro("Piriquito")
Vandog.comer()
Vandog.amamentar()
Vandog.emitir_som()
Miaumiau.comer()
Miaumiau.amamentar()
Miaumiau.emitir_som()
Piriquito.comer()
Piriquito.emitir_som()

class Animal:

  def __init__(self, nome):
    self.nome = nome
  def emitir_som(self):
    print(f"{self.nome} esta emitindo um som")
class Cachorro(Animal):

  def emitir_som(self):
    print(f"{self.nome} Au Au")

class Gato(Animal):

  def emitir_som(self):
    print(f"{self.nome} Miau")

for animal in [Cachorro("Davi"), Gato("Garfield"), Animal ("Bicho")]:
  animal.emitir_som()

class Veiculo:
    def __init__(self, marca, modelo):
        self.marca = marca
        self.modelo = modelo
        self.__velocidade_atual = 0


    def descricao(self):
        return f"Veículo: {self.marca} {self.modelo}"

    def acelerar(self, valor):
        if valor > 0:
            self.__velocidade_atual += valor

    def get_velocidade_atual(self):
        return self.__velocidade_atual
    def buzinar(self):
        pass

class Carro(Veiculo):

    def buzinar(self):
        return "FOMMMMMMMMMM fom!"

class Moto(Veiculo):
    def buzinar(self):
        return "BIPPPPP bip!"

meu_carro = Carro("Toyota", "Corolla")
minha_moto = Moto("Honda", "CB 500")
print("\nCARRO")
meu_carro.acelerar(60)
minha_moto.acelerar(80)
print(meu_carro.descricao())
print(f"Velocidade Atual: {meu_carro.get_velocidade_atual()} km/h")
print(f"Som da buzina: {meu_carro.buzinar()}")

print("\nMOTO")
print(minha_moto.descricao())
print(f"Velocidade Atual: {minha_moto.get_velocidade_atual()} km/h")
print(f"Som da buzina: {minha_moto.buzinar()}")

"""abstracao
encapsulamento
polimorfismo
heranca

"""